// VidoMove - Social Media Platform Types

export interface User {
  id: string;
  username: string;
  firstName: string;
  lastName: string;
  avatar: string;
  bio: string;
  followers: string[];
  following: string[];
  isLive: boolean;
  stories: Story[];
  posts: Post[];
  reels: Reel[];
}

export interface Story {
  id: string;
  userId: string;
  mediaUrl: string;
  type: 'image' | 'video';
  createdAt: number;
  expiresAt: number;
  views: string[];
}

export interface Post {
  id: string;
  userId: string;
  mediaUrl: string;
  caption: string;
  likes: string[];
  comments: PostComment[];
  createdAt: number;
  type: 'image' | 'video';
}

export interface Reel {
  id: string;
  userId: string;
  videoUrl: string;
  caption: string;
  likes: string[];
  comments: PostComment[];
  views: number;
  createdAt: number;
}

export interface PostComment {
  id: string;
  userId: string;
  text: string;
  createdAt: number;
  likes: string[];
}

export interface Message {
  id: string;
  chatId: string;
  senderId: string;
  text: string;
  createdAt: number;
  editedAt?: number;
  isDeleted: boolean;
  replyTo?: string;
  type: 'text' | 'image' | 'video' | 'call';
  mediaUrl?: string;
  callDuration?: number;
  callType?: 'audio' | 'video';
}

export interface Chat {
  id: string;
  participants: string[];
  messages: Message[];
  background: string;
  isBlocked: boolean;
  blockedBy?: string;
  lastMessageAt: number;
  unreadCount: Record<string, number>;
}

export interface LiveStream {
  id: string;
  userId: string;
  title: string;
  viewers: string[];
  startedAt: number;
  thumbnail?: string;
}

export type Language = 'uz' | 'ru' | 'en' | 'es' | 'fr' | 'de';

export interface Translations {
  [key: string]: string | Translations;
}

export const translations: Record<Language, Translations> = {
  uz: {
    appName: 'VidoMove',
    login: 'Kirish',
    register: 'Ro\'yxatdan o\'tish',
    username: 'Foydalanuvchi nomi',
    password: 'Parol',
    firstName: 'Ism',
    lastName: 'Familiya',
    email: 'Email',
    bio: 'Bio',
    follow: 'Obuna bo\'lish',
    following: 'Obuna bo\'lingan',
    followers: 'Obunachilar',
    posts: 'Postlar',
    reels: 'Reels',
    stories: 'Hikoyalar',
    search: 'Qidirish',
    messages: 'Xabarlar',
    profile: 'Profil',
    home: 'Bosh sahifa',
    create: 'Yaratish',
    settings: 'Sozlamalar',
    language: 'Til',
    logout: 'Chiqish',
    editProfile: 'Profilni tahrirlash',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    delete: 'O\'chirish',
    edit: 'Tahrirlash',
    reply: 'Javob berish',
    send: 'Yuborish',
    typeMessage: 'Xabar yozing...',
    clearChat: 'Chatni tozalash',
    deleteChat: 'Chatni o\'chirish',
    blockUser: 'Foydalanuvchini bloklash',
    unblockUser: 'Blokdan chiqarish',
    startLive: 'Jonli efir',
    endLive: 'Efirdan chiqish',
    live: 'JONLI',
    viewers: 'Tomoshabinlar',
    noAccount: 'Hisobingiz yo\'qmi?',
    haveAccount: 'Hisobingiz bormi?',
    createAccount: 'Hisob yaratish',
    usernameTaken: 'Bu foydalanuvchi nomi band',
    invalidCredentials: 'Noto\'g\'ri ma\'lumotlar',
    chatBackground: 'Chat fonini o\'zgartirish',
    videoCall: 'Video qo\'ng\'iroq',
    audioCall: 'Ovozli qo\'ng\'iroq',
    callEnded: 'Qo\'ng\'iroq tugadi',
    incomingCall: 'Kiruvchi qo\'ng\'iroq',
    accept: 'Qabul qilish',
    decline: 'Rad etish',
    storyViews: 'Ko\'rishlar',
    addStory: 'Hikoya qo\'shish',
    addPost: 'Post qo\'shish',
    addReel: 'Reel qo\'shish',
    explore: 'Kashf qilish',
    notifications: 'Bildirishnomalar',
    likedYourPost: 'sizning postingizni yoqdi',
    startedFollowing: 'sizga obuna bo\'ldi',
    commented: 'izoh qoldirdi',
    mentioned: 'sizni eslatdi',
    noMessages: 'Xabarlar yo\'q',
    noPosts: 'Postlar yo\'q',
    noStories: 'Hikoyalar yo\'q',
    searchUsers: 'Foydalanuvchilarni qidirish...',
    noResults: 'Natijalar yo\'q',
    loading: 'Yuklanmoqda...',
    error: 'Xatolik yuz berdi',
    retry: 'Qayta urinish',
    cameraPermission: 'Kamera ruxsati kerak',
    microphonePermission: 'Mikrofon ruxsati kerak',
    allow: 'Ruxsat berish',
    deny: 'Rad etish',
    goLive: 'Jonli efirga o\'tish',
    streamTitle: 'Efir sarlavhasi',
    startStreaming: 'Efirdan boshlash',
    endStreaming: 'Efirdan tugatish',
    share: 'Ulashish',
    report: 'Shikoyat qilish',
    copyLink: 'Havolani nusxalash',
    bookmark: 'Saqlash',
    bookmarks: 'Saqlanganlar',
    removeBookmark: 'Saqlanganlardan olib tashlash',
    tags: 'Teglar',
    location: 'Joylashuv',
    addLocation: 'Joylashuv qo\'shish',
    addTag: 'Teg qo\'shish',
    writeCaption: 'Tavsif yozing...',
    post: 'Post',
    next: 'Keyingi',
    back: 'Orqaga',
    done: 'Tayyor',
    skip: 'O\'tkazib yuborish',
    continue: 'Davom etish',
    confirm: 'Tasdiqlash',
    areYouSure: 'Ishonchingiz komilmi?',
    actionCannotBeUndone: 'Bu amalni bekor qilib bo\'lmaydi',
    yes: 'Ha',
    no: 'Yo\'q',
    close: 'Yopish',
    open: 'Ochish',
    more: 'Ko\'proq',
    less: 'Kamroq',
    seeAll: 'Hammasini ko\'rish',
    seeLess: 'Kamroq ko\'rish',
    new: 'Yangi',
    trending: 'Mashhur',
    recommended: 'Tavsiya etilgan',
    forYou: 'Siz uchun',
    followingFeed: 'Obunalar',
    discover: 'Kashf qilish',
  },
  ru: {
    appName: 'VidoMove',
    login: 'Вход',
    register: 'Регистрация',
    username: 'Имя пользователя',
    password: 'Пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    email: 'Email',
    bio: 'О себе',
    follow: 'Подписаться',
    following: 'Подписки',
    followers: 'Подписчики',
    posts: 'Посты',
    reels: 'Reels',
    stories: 'Истории',
    search: 'Поиск',
    messages: 'Сообщения',
    profile: 'Профиль',
    home: 'Главная',
    create: 'Создать',
    settings: 'Настройки',
    language: 'Язык',
    logout: 'Выйти',
    editProfile: 'Редактировать профиль',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Редактировать',
    reply: 'Ответить',
    send: 'Отправить',
    typeMessage: 'Напишите сообщение...',
    clearChat: 'Очистить чат',
    deleteChat: 'Удалить чат',
    blockUser: 'Заблокировать',
    unblockUser: 'Разблокировать',
    startLive: 'Прямой эфир',
    endLive: 'Завершить эфир',
    live: 'В ЭФИРЕ',
    viewers: 'Зрители',
    noAccount: 'Нет аккаунта?',
    haveAccount: 'Есть аккаунт?',
    createAccount: 'Создать аккаунт',
    usernameTaken: 'Имя пользователя занято',
    invalidCredentials: 'Неверные данные',
    chatBackground: 'Изменить фон чата',
    videoCall: 'Видеозвонок',
    audioCall: 'Аудиозвонок',
    callEnded: 'Звонок завершен',
    incomingCall: 'Входящий звонок',
    accept: 'Принять',
    decline: 'Отклонить',
    storyViews: 'Просмотры',
    addStory: 'Добавить историю',
    addPost: 'Добавить пост',
    addReel: 'Добавить reel',
    explore: 'Обзор',
    notifications: 'Уведомления',
    likedYourPost: 'понравился ваш пост',
    startedFollowing: 'подписался на вас',
    commented: 'прокомментировал',
    mentioned: 'упомянул вас',
    noMessages: 'Нет сообщений',
    noPosts: 'Нет постов',
    noStories: 'Нет историй',
    searchUsers: 'Поиск пользователей...',
    noResults: 'Нет результатов',
    loading: 'Загрузка...',
    error: 'Произошла ошибка',
    retry: 'Повторить',
    cameraPermission: 'Требуется доступ к камере',
    microphonePermission: 'Требуется доступ к микрофону',
    allow: 'Разрешить',
    deny: 'Отклонить',
    goLive: 'Начать прямой эфир',
    streamTitle: 'Название эфира',
    startStreaming: 'Начать трансляцию',
    endStreaming: 'Завершить трансляцию',
    share: 'Поделиться',
    report: 'Пожаловаться',
    copyLink: 'Копировать ссылку',
    bookmark: 'Сохранить',
    bookmarks: 'Сохраненное',
    removeBookmark: 'Удалить из сохраненного',
    tags: 'Теги',
    location: 'Местоположение',
    addLocation: 'Добавить местоположение',
    addTag: 'Добавить тег',
    writeCaption: 'Напишите подпись...',
    post: 'Опубликовать',
    next: 'Далее',
    back: 'Назад',
    done: 'Готово',
    skip: 'Пропустить',
    continue: 'Продолжить',
    confirm: 'Подтвердить',
    areYouSure: 'Вы уверены?',
    actionCannotBeUndone: 'Это действие нельзя отменить',
    yes: 'Да',
    no: 'Нет',
    close: 'Закрыть',
    open: 'Открыть',
    more: 'Еще',
    less: 'Меньше',
    seeAll: 'Смотреть все',
    seeLess: 'Смотреть меньше',
    new: 'Новое',
    trending: 'Популярное',
    recommended: 'Рекомендуемое',
    forYou: 'Для вас',
    followingFeed: 'Подписки',
    discover: 'Найти',
  },
  en: {
    appName: 'VidoMove',
    login: 'Login',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    bio: 'Bio',
    follow: 'Follow',
    following: 'Following',
    followers: 'Followers',
    posts: 'Posts',
    reels: 'Reels',
    stories: 'Stories',
    search: 'Search',
    messages: 'Messages',
    profile: 'Profile',
    home: 'Home',
    create: 'Create',
    settings: 'Settings',
    language: 'Language',
    logout: 'Logout',
    editProfile: 'Edit Profile',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    reply: 'Reply',
    send: 'Send',
    typeMessage: 'Type a message...',
    clearChat: 'Clear Chat',
    deleteChat: 'Delete Chat',
    blockUser: 'Block User',
    unblockUser: 'Unblock User',
    startLive: 'Go Live',
    endLive: 'End Live',
    live: 'LIVE',
    viewers: 'Viewers',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    usernameTaken: 'Username is already taken',
    invalidCredentials: 'Invalid credentials',
    chatBackground: 'Change Chat Background',
    videoCall: 'Video Call',
    audioCall: 'Audio Call',
    callEnded: 'Call Ended',
    incomingCall: 'Incoming Call',
    accept: 'Accept',
    decline: 'Decline',
    storyViews: 'Views',
    addStory: 'Add Story',
    addPost: 'Add Post',
    addReel: 'Add Reel',
    explore: 'Explore',
    notifications: 'Notifications',
    likedYourPost: 'liked your post',
    startedFollowing: 'started following you',
    commented: 'commented',
    mentioned: 'mentioned you',
    noMessages: 'No messages',
    noPosts: 'No posts',
    noStories: 'No stories',
    searchUsers: 'Search users...',
    noResults: 'No results',
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    cameraPermission: 'Camera permission required',
    microphonePermission: 'Microphone permission required',
    allow: 'Allow',
    deny: 'Deny',
    goLive: 'Go Live',
    streamTitle: 'Stream Title',
    startStreaming: 'Start Streaming',
    endStreaming: 'End Streaming',
    share: 'Share',
    report: 'Report',
    copyLink: 'Copy Link',
    bookmark: 'Bookmark',
    bookmarks: 'Bookmarks',
    removeBookmark: 'Remove Bookmark',
    tags: 'Tags',
    location: 'Location',
    addLocation: 'Add Location',
    addTag: 'Add Tag',
    writeCaption: 'Write a caption...',
    post: 'Post',
    next: 'Next',
    back: 'Back',
    done: 'Done',
    skip: 'Skip',
    continue: 'Continue',
    confirm: 'Confirm',
    areYouSure: 'Are you sure?',
    actionCannotBeUndone: 'This action cannot be undone',
    yes: 'Yes',
    no: 'No',
    close: 'Close',
    open: 'Open',
    more: 'More',
    less: 'Less',
    seeAll: 'See All',
    seeLess: 'See Less',
    new: 'New',
    trending: 'Trending',
    recommended: 'Recommended',
    forYou: 'For You',
    followingFeed: 'Following',
    discover: 'Discover',
  },
  es: {
    appName: 'VidoMove',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    username: 'Nombre de usuario',
    password: 'Contraseña',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Email',
    bio: 'Biografía',
    follow: 'Seguir',
    following: 'Siguiendo',
    followers: 'Seguidores',
    posts: 'Publicaciones',
    reels: 'Reels',
    stories: 'Historias',
    search: 'Buscar',
    messages: 'Mensajes',
    profile: 'Perfil',
    home: 'Inicio',
    create: 'Crear',
    settings: 'Configuración',
    language: 'Idioma',
    logout: 'Cerrar sesión',
    editProfile: 'Editar perfil',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    reply: 'Responder',
    send: 'Enviar',
    typeMessage: 'Escribe un mensaje...',
    clearChat: 'Borrar chat',
    deleteChat: 'Eliminar chat',
    blockUser: 'Bloquear usuario',
    unblockUser: 'Desbloquear usuario',
    startLive: 'En vivo',
    endLive: 'Finalizar en vivo',
    live: 'EN VIVO',
    viewers: 'Espectadores',
    noAccount: '¿No tienes cuenta?',
    haveAccount: '¿Ya tienes cuenta?',
    createAccount: 'Crear cuenta',
    usernameTaken: 'Nombre de usuario no disponible',
    invalidCredentials: 'Credenciales inválidas',
    chatBackground: 'Cambiar fondo del chat',
    videoCall: 'Videollamada',
    audioCall: 'Llamada de audio',
    callEnded: 'Llamada finalizada',
    incomingCall: 'Llamada entrante',
    accept: 'Aceptar',
    decline: 'Rechazar',
    storyViews: 'Vistas',
    addStory: 'Añadir historia',
    addPost: 'Añadir publicación',
    addReel: 'Añadir reel',
    explore: 'Explorar',
    notifications: 'Notificaciones',
    likedYourPost: 'le gustó tu publicación',
    startedFollowing: 'comenzó a seguirte',
    commented: 'comentó',
    mentioned: 'te mencionó',
    noMessages: 'No hay mensajes',
    noPosts: 'No hay publicaciones',
    noStories: 'No hay historias',
    searchUsers: 'Buscar usuarios...',
    noResults: 'Sin resultados',
    loading: 'Cargando...',
    error: 'Ocurrió un error',
    retry: 'Reintentar',
    cameraPermission: 'Se requiere permiso de cámara',
    microphonePermission: 'Se requiere permiso de micrófono',
    allow: 'Permitir',
    deny: 'Denegar',
    goLive: 'Ir en vivo',
    streamTitle: 'Título de la transmisión',
    startStreaming: 'Iniciar transmisión',
    endStreaming: 'Finalizar transmisión',
    share: 'Compartir',
    report: 'Reportar',
    copyLink: 'Copiar enlace',
    bookmark: 'Guardar',
    bookmarks: 'Guardados',
    removeBookmark: 'Eliminar de guardados',
    tags: 'Etiquetas',
    location: 'Ubicación',
    addLocation: 'Añadir ubicación',
    addTag: 'Añadir etiqueta',
    writeCaption: 'Escribe un pie de foto...',
    post: 'Publicar',
    next: 'Siguiente',
    back: 'Atrás',
    done: 'Hecho',
    skip: 'Omitir',
    continue: 'Continuar',
    confirm: 'Confirmar',
    areYouSure: '¿Estás seguro?',
    actionCannotBeUndone: 'Esta acción no se puede deshacer',
    yes: 'Sí',
    no: 'No',
    close: 'Cerrar',
    open: 'Abrir',
    more: 'Más',
    less: 'Menos',
    seeAll: 'Ver todo',
    seeLess: 'Ver menos',
    new: 'Nuevo',
    trending: 'Tendencias',
    recommended: 'Recomendado',
    forYou: 'Para ti',
    followingFeed: 'Siguiendo',
    discover: 'Descubrir',
  },
  fr: {
    appName: 'VidoMove',
    login: 'Connexion',
    register: 'S\'inscrire',
    username: 'Nom d\'utilisateur',
    password: 'Mot de passe',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    bio: 'Bio',
    follow: 'Suivre',
    following: 'Abonnements',
    followers: 'Abonnés',
    posts: 'Publications',
    reels: 'Reels',
    stories: 'Stories',
    search: 'Rechercher',
    messages: 'Messages',
    profile: 'Profil',
    home: 'Accueil',
    create: 'Créer',
    settings: 'Paramètres',
    language: 'Langue',
    logout: 'Déconnexion',
    editProfile: 'Modifier le profil',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    reply: 'Répondre',
    send: 'Envoyer',
    typeMessage: 'Écrivez un message...',
    clearChat: 'Effacer la discussion',
    deleteChat: 'Supprimer la discussion',
    blockUser: 'Bloquer',
    unblockUser: 'Débloquer',
    startLive: 'En direct',
    endLive: 'Terminer le direct',
    live: 'EN DIRECT',
    viewers: 'Spectateurs',
    noAccount: 'Pas de compte?',
    haveAccount: 'Déjà un compte?',
    createAccount: 'Créer un compte',
    usernameTaken: 'Nom d\'utilisateur déjà pris',
    invalidCredentials: 'Identifiants invalides',
    chatBackground: 'Changer le fond du chat',
    videoCall: 'Appel vidéo',
    audioCall: 'Appel audio',
    callEnded: 'Appel terminé',
    incomingCall: 'Appel entrant',
    accept: 'Accepter',
    decline: 'Refuser',
    storyViews: 'Vues',
    addStory: 'Ajouter une story',
    addPost: 'Ajouter une publication',
    addReel: 'Ajouter un reel',
    explore: 'Explorer',
    notifications: 'Notifications',
    likedYourPost: 'a aimé votre publication',
    startedFollowing: 'vous suit',
    commented: 'a commenté',
    mentioned: 'vous a mentionné',
    noMessages: 'Pas de messages',
    noPosts: 'Pas de publications',
    noStories: 'Pas de stories',
    searchUsers: 'Rechercher des utilisateurs...',
    noResults: 'Aucun résultat',
    loading: 'Chargement...',
    error: 'Une erreur s\'est produite',
    retry: 'Réessayer',
    cameraPermission: 'Autorisation caméra requise',
    microphonePermission: 'Autorisation microphone requise',
    allow: 'Autoriser',
    deny: 'Refuser',
    goLive: 'Passer en direct',
    streamTitle: 'Titre du stream',
    startStreaming: 'Commencer le stream',
    endStreaming: 'Terminer le stream',
    share: 'Partager',
    report: 'Signaler',
    copyLink: 'Copier le lien',
    bookmark: 'Enregistrer',
    bookmarks: 'Enregistré',
    removeBookmark: 'Retirer des enregistrements',
    tags: 'Tags',
    location: 'Lieu',
    addLocation: 'Ajouter un lieu',
    addTag: 'Ajouter un tag',
    writeCaption: 'Écrivez une légende...',
    post: 'Publier',
    next: 'Suivant',
    back: 'Retour',
    done: 'Terminé',
    skip: 'Passer',
    continue: 'Continuer',
    confirm: 'Confirmer',
    areYouSure: 'Êtes-vous sûr?',
    actionCannotBeUndone: 'Cette action est irréversible',
    yes: 'Oui',
    no: 'Non',
    close: 'Fermer',
    open: 'Ouvrir',
    more: 'Plus',
    less: 'Moins',
    seeAll: 'Voir tout',
    seeLess: 'Voir moins',
    new: 'Nouveau',
    trending: 'Tendances',
    recommended: 'Recommandé',
    forYou: 'Pour vous',
    followingFeed: 'Abonnements',
    discover: 'Découvrir',
  },
  de: {
    appName: 'VidoMove',
    login: 'Anmelden',
    register: 'Registrieren',
    username: 'Benutzername',
    password: 'Passwort',
    firstName: 'Vorname',
    lastName: 'Nachname',
    email: 'Email',
    bio: 'Bio',
    follow: 'Folgen',
    following: 'Folge ich',
    followers: 'Follower',
    posts: 'Beiträge',
    reels: 'Reels',
    stories: 'Stories',
    search: 'Suchen',
    messages: 'Nachrichten',
    profile: 'Profil',
    home: 'Startseite',
    create: 'Erstellen',
    settings: 'Einstellungen',
    language: 'Sprache',
    logout: 'Abmelden',
    editProfile: 'Profil bearbeiten',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    reply: 'Antworten',
    send: 'Senden',
    typeMessage: 'Nachricht schreiben...',
    clearChat: 'Chat löschen',
    deleteChat: 'Chat entfernen',
    blockUser: 'Benutzer blockieren',
    unblockUser: 'Benutzer entblockieren',
    startLive: 'Live gehen',
    endLive: 'Live beenden',
    live: 'LIVE',
    viewers: 'Zuschauer',
    noAccount: 'Kein Konto?',
    haveAccount: 'Bereits ein Konto?',
    createAccount: 'Konto erstellen',
    usernameTaken: 'Benutzername bereits vergeben',
    invalidCredentials: 'Ungültige Anmeldedaten',
    chatBackground: 'Chat-Hintergrund ändern',
    videoCall: 'Videoanruf',
    audioCall: 'Sprachanruf',
    callEnded: 'Anruf beendet',
    incomingCall: 'Eingehender Anruf',
    accept: 'Annehmen',
    decline: 'Ablehnen',
    storyViews: 'Aufrufe',
    addStory: 'Story hinzufügen',
    addPost: 'Beitrag hinzufügen',
    addReel: 'Reel hinzufügen',
    explore: 'Entdecken',
    notifications: 'Benachrichtigungen',
    likedYourPost: 'hat deinen Beitrag geliked',
    startedFollowing: 'folgt dir jetzt',
    commented: 'hat kommentiert',
    mentioned: 'hat dich erwähnt',
    noMessages: 'Keine Nachrichten',
    noPosts: 'Keine Beiträge',
    noStories: 'Keine Stories',
    searchUsers: 'Benutzer suchen...',
    noResults: 'Keine Ergebnisse',
    loading: 'Laden...',
    error: 'Ein Fehler ist aufgetreten',
    retry: 'Wiederholen',
    cameraPermission: 'Kamera-Berechtigung erforderlich',
    microphonePermission: 'Mikrofon-Berechtigung erforderlich',
    allow: 'Erlauben',
    deny: 'Ablehnen',
    goLive: 'Live gehen',
    streamTitle: 'Stream-Titel',
    startStreaming: 'Stream starten',
    endStreaming: 'Stream beenden',
    share: 'Teilen',
    report: 'Melden',
    copyLink: 'Link kopieren',
    bookmark: 'Speichern',
    bookmarks: 'Gespeichert',
    removeBookmark: 'Aus Gespeichert entfernen',
    tags: 'Tags',
    location: 'Ort',
    addLocation: 'Ort hinzufügen',
    addTag: 'Tag hinzufügen',
    writeCaption: 'Bildunterschrift schreiben...',
    post: 'Posten',
    next: 'Weiter',
    back: 'Zurück',
    done: 'Fertig',
    skip: 'Überspringen',
    continue: 'Fortfahren',
    confirm: 'Bestätigen',
    areYouSure: 'Bist du sicher?',
    actionCannotBeUndone: 'Diese Aktion kann nicht rückgängig gemacht werden',
    yes: 'Ja',
    no: 'Nein',
    close: 'Schließen',
    open: 'Öffnen',
    more: 'Mehr',
    less: 'Weniger',
    seeAll: 'Alle anzeigen',
    seeLess: 'Weniger anzeigen',
    new: 'Neu',
    trending: 'Trending',
    recommended: 'Empfohlen',
    forYou: 'Für dich',
    followingFeed: 'Folge ich',
    discover: 'Entdecken',
  },
};

export const chatBackgrounds = [
  { id: 'default', name: 'Default', gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)' },
  { id: 'ocean', name: 'Ocean', gradient: 'linear-gradient(135deg, #0066cc 0%, #00ccff 100%)' },
  { id: 'sunset', name: 'Sunset', gradient: 'linear-gradient(135deg, #ff6b35 0%, #f7931e 100%)' },
  { id: 'forest', name: 'Forest', gradient: 'linear-gradient(135deg, #134e13 0%, #2d5a2d 100%)' },
  { id: 'purple', name: 'Purple', gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' },
  { id: 'pink', name: 'Pink', gradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)' },
  { id: 'dark', name: 'Dark', gradient: 'linear-gradient(135deg, #232526 0%, #414345 100%)' },
  { id: 'gold', name: 'Gold', gradient: 'linear-gradient(135deg, #f5af19 0%, #f12711 100%)' },
  { id: 'mint', name: 'Mint', gradient: 'linear-gradient(135deg, #00b09b 0%, #96c93d 100%)' },
  { id: 'berry', name: 'Berry', gradient: 'linear-gradient(135deg, #8e2de2 0%, #4a00e0 100%)' },
];
